---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: git-branch

outputs:
- name: lint-reports

run:
  path: concourse-configs/tasks/scripts/lint.sh