---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: drupal-app-git

outputs:
- name: lint-reports

run:
  path: drupal-app-git/ci/tasks/scripts/lint.sh