---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: concourse-configs
- name: git-branch

run:
  path: concourse-configs/tasks/scripts/pcf.sh