---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: concourse-configs

run:
  path: concourse-configs/tasks/scripts/ui-tests.sh

